import type { Metadata } from "next";
import "./globals.css";
import CartComponent from "./components/CartComponent";
import { CartProvider } from "./context/CartProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>
        <body>{children}</body>
      </CartProvider>
    </html>
  );
}
