import type { Metadata } from "next";
import "./globals.css";
import CartComponent from "./components/CartComponent";
import { CartProvider } from "./context/CartProvider";
import { StoreProvider } from "./context/StoreProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>
        <StoreProvider>
          <body>{children}</body>
        </StoreProvider>
      </CartProvider>
    </html>
  );
}
